# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: BTL_LTNC

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

#Build java jdk 21
#Setup Gradle
#Build with Gradle
#Publish to GitHub Packages
#The USERNAME and TOKEN need to correspond to the credentials environment variables used in the publishing section of your build.gradle
#The GITHUB_TOKEN secret is provided by GitHub Actions and can be used to authenticate in order to publish the package
#The USERNAME is the GitHub username of the actor that triggered the action
#The TOKEN is the GitHub token of the actor that triggered the action
#The USERNAME and TOKEN are passed as environment variables to the Gradle build
#The USERNAME and TOKEN are used in the publishing section of the build.gradle file to authenticate with GitHub Packages

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '21'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Publish to GitHub Packages
      run: ./gradlew publish
      env:
        USERNAME: ${{ github.actor }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}