name: Deploy static content to Pages

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      
      - name: Setup JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'

      
      - name: Set up Gradle
        uses: eskatos/gradle-command-action@v2
        with:
          arguments: setHomepagePath -PhomepagePath=src/main/resources/templates/Hospital_Home/Home.html builds

      - name: Build with Gradle
        run: ./gradlew setHomepagePath -PhomepagePath=src/main/resources/templates/Hospital_Home/Home.html build
      - name: Copy build artifacts
        run: cp -r build/* $GITHUB_WORKSPACE

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
        with:
          path: src/main/resources/templates/Hospital_Home/Home.html

      